import type { Metadata } from "next";
import { AuthProvider } from "@descope/nextjs-sdk";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const projectId = process.env.NEXT_PUBLIC_DESCOPE_PROJECT_ID;
  const cookieOption ={
    sameSite : "Lax" as const,
    secure : process.env.NODE_ENV !== "development",
  };

  if (!projectId) {
    throw new Error("NEXT_PUBLIC_DESCOPE_PROJECT_ID is not configured");
  }

  return (
    <AuthProvider projectId={projectId}>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </AuthProvider>
  );
}
